version: "3"
services:
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./dump:/dump

  node:
    image: "node:carbon"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3030:3030"
    command: bash -c "yarn install; npx browserslist@latest --update-db; yarn build; mongorestore; yarn start"
    depends_on:
      - mongo
 